class ValidationError(Exception):
    pass


class NotFoundError(Exception):
    pass
